name: Packaging on Windows

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  windowsbuild:
    runs-on: windows-2019
    steps:
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: v2.8.5
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: config
        run: xmake config --yes -vD
      - name: build
        run: xmake build --yes -vD s7
      - name: install
        run: xmake install --yes -vD s7
      - name: Upload 
        uses: actions/upload-artifact@v3
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          path: build/s7_*
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: build/s7_*

