name: Build on macOS 11

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  macosbuild:
    runs-on: macos-11
    steps:
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: v2.8.5
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: config
        run: xmake config --yes -vD -m releasedbg
      - name: build
        run: xmake build --yes -vD s7
      - name: test
        run: xmake run --yes -vD plus.scm
